@Library('engineering-standards') _

standardPipeline(
    appName: 'portfolio-service',
    language: 'python',
    runStaticChecks: true,
    runUnitTests: true,
    runSecurityScan: true,
    requireDeploymentApproval: true
)
